twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: [ 'bootstrap_4_layout.html.twig' ]
    globals:
        userRepository: '@App\Repository\UserRepository'
        commandeRepository: '@App\Repository\CommandeRepository'
        serviceCommand: '@App\Service\ServiceCommande'